name: Publish Ruby gem
on:
  push:
    tags: 'v*'
  workflow_dispatch:
concurrency:
  group: '${{ github.workflow }} @ github.ref }}'
  cancel-in-progress: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.2'
      - name: Build and publish to GitHub Packages
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --key github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: 'Bearer ${{ secrets.GITHUB_TOKEN }}'
          OWNER: '${{ github.repository_owner }}'
